### ISSUE TITLE
BSus > Sus (?)

### ISSUE THREAD

**Issue by versotym** [pruizf/disco#1]
https://github.com/pruizf/disco/blob/c6f21f78f98ab58f3277b3e67a76b47d2e613508/tei/19th/per-sonnet/Flores_Roa%2C_Julio__580n~~A_mi_madre__2111.xml#L140`

**Comment by pruizf** [comment]
Thanks for this issue.

It's fixed now. Was already with the typo in the source: http://www.cervantesvirtual.com/obra-visor/sonetos-del-siglo-xix--0/html/00199522-82b2-11df-acc7-002185ce6064_16.html#I_260_
