### ISSUE TITLE
tanto4 > tanto

### ISSUE THREAD

**Issue by versotym** [pruizf/disco#2]
https://github.com/pruizf/disco/blob/c6f21f78f98ab58f3277b3e67a76b47d2e613508/tei/15th-17th/per-sonnet/Jauregui%2C_Juan_de__089g~~En_el_t%C3%BAmulo_que_fabric%C3%B3_Sevilla_a_la_reina_Do%C3%B1a_M__0174.xml#L134

**Comment by pruizf** [comment]
Thanks for this issue.

Fixed as of 91992c5.

The source already had the typo: http://www.cervantesvirtual.com/obra-visor/sonetos-del-siglo-xv-al-xvii--0/html/001213e2-82b2-11df-acc7-002185ce6064_10.html#I_267_
